"""Assessment control plane; additive schema only. Historical migrations stay frozen."""
from alembic import op
import sqlalchemy as sa
revision = '20260915_0014'
down_revision = '20260914_0013'
branch_labels = depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('web_base_url', sa.String(length=512), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=False),
    sa.Column('credential_env', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_private', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key', 'web_base_url', name='uq_connection_tenant_web')
    )
    op.create_index(op.f('ix_github_connections_tenant_key'), 'github_connections', ['tenant_key'], unique=False)
    op.create_table('local_ai_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_key', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key')
    )
    op.create_table('recon_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key', 'name', name='uq_recon_profile_tenant_name')
    )
    op.create_index(op.f('ix_recon_profiles_tenant_key'), 'recon_profiles', ['tenant_key'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_profile', sa.JSON(), nullable=False),
    sa.Column('scan_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_tenant_key'), 'assessments', ['tenant_key'], unique=False)
    op.create_table('ai_advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'fingerprint', name='uq_ai_advice_input')
    )
    op.create_index(op.f('ix_ai_advice_assessment_id'), 'ai_advice', ['assessment_id'], unique=False)
    op.create_table('assessment_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['github_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'entity_type', 'entity_id', name='uq_assessment_entity')
    )
    op.create_index(op.f('ix_assessment_entities_assessment_id'), 'assessment_entities', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_entities_entity_id'), 'assessment_entities', ['entity_id'], unique=False)
    op.create_table('assessment_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['github_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'identity', name='uq_assessment_target_identity')
    )
    op.create_index(op.f('ix_assessment_targets_assessment_id'), 'assessment_targets', ['assessment_id'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_scan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['scheduled_scan_id'], ['scheduled_scans.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['assessment_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_scan_id')
    )
    op.create_index(op.f('ix_assessment_runs_assessment_id'), 'assessment_runs', ['assessment_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('assessment_runs')
    op.drop_table('assessment_targets')
    op.drop_table('assessment_entities')
    op.drop_table('ai_advice')
    op.drop_table('assessments')
    op.drop_table('recon_profiles')
    op.drop_table('local_ai_configurations')
    op.drop_table('github_connections')
